### ISSUE TITLE
Question about performance analysis

### ISSUE THREAD

**Issue by jzakirov** [Jack-guo-xy/Python-IW-SSIM#2]
Hi! Thank you for PyTorch version of IW-SSIM, it really saved a lot of my time.

One question I have is about you performance analysis. Can you share the code or give an explanation of how you do that?
As far as I know standard way of performing PLCC and SRCC computation is by first fitting 5 parametric non-linear regression between predicted scores and subjective scores.
In original paper it's stated that

>  ... where  a1 to a5 are model parameters found numerically using a nonlinear regression process in MATLAB opti- mization toolbox to maximize the correlations between subjective and objective scores.

So I try to do the same, fit regression (written on PyTorch) and maximise pearson correlation between scores. But results I get for TID2013 are quite different from yours (~0.77 PLCC and ~0.78 SRCC). I also noticed that usage of different optimizers, learning rates and number of optimization steps may lead to different results. Are using MATLAB to fit regression?

**Comment by Jack-guo-xy** [comment]
> Hi! Thank you for PyTorch version of IW-SSIM, it really saved a lot of my time.
> 
> One question I have is about you performance analysis. Can you share the code or give an explanation of how you do that?
> As far as I know standard way of performing PLCC and SRCC computation is by first fitting 5 parametric non-linear regression between predicted scores and subjective scores.
> In original paper it's stated that
> 
> > ... where  a1 to a5 are model parameters found numerically using a nonlinear regression process in MATLAB opti- mization toolbox to maximize the correlations between subjective and objective scores.
> 
> So I try to do the same, fit regression (written on PyTorch) and maximise pearson correlation between scores. But results I get for TID2013 are quite different from yours (~0.77 PLCC and ~0.78 SRCC). I also noticed that usage of different optimizers, learning rates and number of optimization steps may lead to different results. Are using MATLAB to fit regression?

Hi! Actually different fitting methods and different initial parameters can get quite different final PLCC results. I'm using Matlab to fit. I think you can check whether our SRCC is the same since this is a rank correlation, it assumes to not be changed wrt. fitting.
